export const LocalAssets = {
  fonts: {
    "Poppins-Black": require("./fonts/Poppins-Black.ttf"),
    "Poppins-Bold": require("./fonts/Poppins-Bold.ttf"),
    "Poppins-ExtraBold": require("./fonts/Poppins-ExtraBold.ttf"),
    "Poppins-ExtraLight": require("./fonts/Poppins-ExtraLight.ttf"),
    "Poppins-Light": require("./fonts/Poppins-Light.ttf"),
    "Poppins-Medium": require("./fonts/Poppins-Medium.ttf"),
    "Poppins-Regular": require("./fonts/Poppins-Regular.ttf"),
    "Poppins-SemiBold": require("./fonts/Poppins-SemiBold.ttf"),
    "Poppins-Thin": require("./fonts/Poppins-Thin.ttf"),
  },
  icons: {
    bookmark: require("./icons/bookmark.png"),
    home: require("./icons/home.png"),
    plus: require("./icons/home.png"),
    profile: require("./icons/profile.png"),
    leftArrow: require("./icons/left-arrow.png"),
    menu: require("./icons/menu.png"),
    search: require("./icons/search.png"),
    upload: require("./icons/upload.png"),
    rightArrow: require("./icons/right-arrow.png"),
    logout: require("./icons/logout.png"),
    eyeHide: require("./icons/eye-hide.png"),
    eye: require("./icons/eye.png"),
    play: require("./icons/play.png"),
  },
  images: {
    cards: require("./images/cards.png"),
    empty: require("./images/empty.png"),
    logo: require("./images/logo.png"),
    logoSmall: require("./images/logo-small.png"),
    path: require("./images/path.png"),
    profile: require("./images/profile.png"),
    thumbnail: require("./images/thumbnail.png"),
  },
};
